apiVersion: v1
kind: Pod
metadata:
  name: carlospolop-node-pp-dless
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: node-pp-dless
    image: carlospolop/node-pp-dless:amd
    securityContext:
      runAsUser: 1000
      readOnlyRootFilesystem: true
    ports:
    - containerPort: 3000
  restartPolicy: OnFailure
