apiVersion: v1
kind: Pod
metadata:
  name: dless-express-pp-pod
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: dless-express-pp-pod
    image: dless-express-pp
    imagePullPolicy: Never
    securityContext:
      runAsUser: 1000
      readOnlyRootFilesystem: true
  restartPolicy: OnFailure

---

apiVersion: v1
kind: Pod
metadata:
  name: dless-python-rce-pod
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: dless-python-rce-pod
    image: dless-python-rce
    imagePullPolicy: Never
    securityContext:
      runAsUser: 1000
      readOnlyRootFilesystem: true
  restartPolicy: OnFailure

---

apiVersion: v1
kind: Pod
metadata:
  name: dless-flask-ssti-pod
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: dless-flask-ssti-pod
    image: dless-flask-ssti
    imagePullPolicy: Never
    securityContext:
      runAsUser: 1000
      readOnlyRootFilesystem: true
  restartPolicy: OnFailure

---

apiVersion: v1
kind: Pod
metadata:
  name: php-pod
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: php-container
    image: cgr.dev/chainguard/php
    securityContext:
      runAsUser: 1000
      readOnlyRootFilesystem: true
  restartPolicy: OnFailure

---

apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep", "infinity"]
  restartPolicy: OnFailure
