apiVersion: v1
kind: Pod
metadata:
  name: dless-express-pp-pod
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: dless-express-pp-pod
    image: docker.io/carlospolop/dless-express-pp
    securityContext:
      runAsUser: 1000
      readOnlyRootFilesystem: true
  restartPolicy: OnFailure

---

apiVersion: v1
kind: Pod
metadata:
  name: dless-python-rce-pod
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: dless-python-rce-pod
    image: docker.io/carlospolop/dless-python-rce
    securityContext:
      runAsUser: 1000
      readOnlyRootFilesystem: true
  restartPolicy: OnFailure

---

apiVersion: v1
kind: Pod
metadata:
  name: dless-flask-ssti-pod
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: dless-flask-ssti-pod
    image: docker.io/carlospolop/dless-flask-ssti
    securityContext:
      runAsUser: 1000
      readOnlyRootFilesystem: true
  restartPolicy: OnFailure

---

apiVersion: v1
kind: Pod
metadata:
  name: php-pod
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: php-container
    image: cgr.dev/chainguard/php
    command: ["php", "-r", "while (true) { sleep(100); }"]
    securityContext:
      runAsUser: 1000
      readOnlyRootFilesystem: true
  restartPolicy: OnFailure

---

apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep", "infinity"]
  restartPolicy: OnFailure
